# Basic
title: Christy Ren
subtitle: Welcome To My Blog
description: Life, Work, Travel, Culture
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ChristyRen
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: My Photo
url: "christyren.github.io"

# # Comment
# comment:
#     provider: duoshuo
#     duoshuo:
#     short_name: robotkang

# Social
social:
    weibo: 123456789
    # weixing: kang1390305137 
    github: christyren
    facebook: mengyuan.ren.16
    mail: christyren@wustl.edu
    # csdn: robotkang

ga: 
    id: UA-180761069-1


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/MengZheK/kangblog.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


# permalink: /:year/:month/:title/

permalink: /:short_year:i_month:i_day.html
# ä¼ª postid çš„æ–¹æ¡ˆ,ä¾¿äºç½‘ç«™ SEO


# Format

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog Home

# Navigation buttons in the front page.s
nav:
    - {title: All Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}   
    - {title: Comments, description: liuyan, url: '/liuyan'}
    - {title: Resources, description: ziyuan, url: '/ziyuan'}
    - {title: About Me, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"






