<<<<<<< HEAD
# Basic
title: æ½˜æŸä¿¡
subtitle: ä¸ªäººç«™
description: æ¬¢è¿Žæ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: leopardpan
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / æœºå™¨å­¦ä¹ 

# baseurl: ""
url: "christyren.github.io"


# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
# enableToc: true

# # Comment
# comment:
#     # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
#     disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
#     weibo: 5366874726 
#     github: leopardpan
#     # zhihu: panpanleopard
#     # juejin: xxx
#     jianshu: 2ada30d8d0f7
#     # twitter: 
#     mail: leopardpan@icloud.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·åŽ»æŽ‰æˆ–è€…æ›´æ¢ id 
# baidu:
#     id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·åŽ»æŽ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-180761069-1
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ðŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}      
    - {title: å…³äºŽæˆ‘, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


=======
title: Chuchen (Leo) Xiong # your name (or website title) here
logo: "/images/My Photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p align="center">
  UMN MSc in Business Analytics
  <br>
  Data Science | Storytelling | Visualization
  <br>
  </p>
  
  
  <a href="mailto:xion2022@umn.edu">Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/chuchen-leo-xiong/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/Xion6cc">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167357228-1 # your Google Analytics tracking ID here
>>>>>>> 738d0ff... first
